"use client";
import { createContext, useContext, useState } from "react";

export const translations = {
  en: {
    nav: {
      home: "HOME",
      product: "PRODUCT",
      benefits: "BENEFITS",
      resources: "RESOURCES",
      install: "Install For Free",
      signin: "Sign In",
      signup: "Sign Up",
    },
    breadcrumb: { home: "Home" },
    hero: {
      line1: "Healthy, comfortable,",
      line2: "and connected",
      sub1: "Monitor air quality, presence, and more anytime,",
      sub2: "anywhere through the Carenuity app.",
    },
    home: {
      aboutTitle: "About us",
      aboutDesc:
        "Carenuity is an intelligent indoor monitoring solution designed to keep homes and loved ones safe, comfortable, and well-ventilated. Powered by advanced environmental sensors, the system tracks air quality, temperature, humidity, pressure, carbon dioxide (CO₂), TVOC levels, and presence in real time. Through the Carenuity mobile app, users can remotely monitor their space, receive insights, and stay connected from anywhere.",
      aboutBtn: "Learn More About Us",
      productsTitle: "Product Lines",
      productsDesc:
        "Flexible solutions designed for different needs — from premium, long-term systems to budget-friendly entry products.",
      whyTitle: "Why Carenuity",
      whyDesc:
        "Carenuity empowers you to monitor and improve your home environment, ensuring comfort, safety, and wellbeing for your loved ones with smart, easy-to-use IoT solutions.",
      awardTitle: "Award",
      awardDesc: "Awarded the BSFZ Seal 2025 for Research & Development",
      awardBody:
        "The red BSFZ Seal, awarded by the Federal Republic of Germany, certifies that Carenuity conducts its own research and development. The SQ-Panel is officially recognized as a result of innovative R&D. The BSFZ Seal is an official quality mark confirming that a product or project is based on research and development. It strengthens trust among customers, partners, and investors by signaling official recognition of innovation and credibility.",
      exploreSystem: "Explore SQ-System",
      exploreC3: "Explore C3-Mini Products",
      products: [
        {
          title: "SQ-System",
          paragraph:
            "A modular premium system for professional air quality monitoring. Designed for permanent installations, scalable environments and long-term use.",
          list: [
            "Modular & expandable",
            "Clean, discreet installation",
            "Privacy-friendly by design",
          ],
        },
        {
          title: "High-quality Design",
          paragraph:
            "Affordable entry solutions that are software-driven and flexible. Ideal for students, startups and developers who want to explore IoT.",
          list: [
            "Affordable entry solutions",
            "Software-driven & flexible",
            "Ideal for students, startups & developers",
          ],
        },
      ],
      whyItems: [
        {
          title: "Home & Families",
          paragraph: "Healthy indoor air for everyday living",
        },
        {
          title: "Offices & Businesses",
          paragraph: "Better air quality for productivity and wellbeing",
        },
        {
          title: "Care & Health",
          paragraph: "Reliable monitoring for sensitive environments",
        },
        {
          title: "Schools & Education",
          paragraph:
            "Modular solutions designed specifically for safe, smart, and well-ventilated learning environments.",
        },
        {
          title: "Home Challenge",
          paragraph:
            "Carenuity Home Challenge lets you build smart home devices and gain hands-on IoT skills.",
        },
      ],
    },
    testimonials: {
      title: "What Our Users Say",
      items: [
        {
          name: "Patrick",
          content:
            "I rely on the Carenuity SQ-Panel to track air quality and stay informed. The historical data is valuable for creating a safer living space.",
          star: 5,
        },
        {
          name: "Patricia",
          content:
            "The Carenuity SQ-Panel has made monitoring air quality simple and effective. The app's real-time alerts give me peace of mind about my family's health.",
          star: 5,
        },
      ],
    },
    sqSystem: {
      heading: "SQ-System",
      description:
        "The Carenuity SQ-System is a modular indoor monitoring solution made up of the SQ-Panel, SQ-Power, SQ-Connector, and SQ-Table Stand, designed to work together as one intelligent unit. At its core, the SQ-Panel houses advanced environmental sensors that continuously measure air quality, temperature, humidity, pressure, carbon dioxide (CO₂), TVOC levels, and presence. The SQ-Power ensures reliable energy supply, while the SQ-Connector enables seamless communication and integration with the Carenuity mobile app for real-time monitoring and commissioning.",
      videoTitle: "Videos showing SQ-Panel and SQ-Power",
      sqPanel: "SQ-Panel",
      sqPower: "SQ-Power",
      products: [
        {
          title: "SQ-Panel",
          paragraph:
            "The Carenuity SQ-Panel monitors air quality, temperature, humidity, pressure, CO₂, TVOC, and presence in real time, sending accurate indoor data to the Carenuity app for healthier, more comfortable spaces.",
          button: "Explore SQ-Panel",
        },
        {
          title: "SQ-Power",
          paragraph:
            "Carenuity SQ-Power is a compact in-wall power module that supplies stable 5 V DC to the SQ-Panel by fitting into a standard flush-mounted electrical box, enabling clean, cable-free installation.",
          button: "Explore SQ-Power",
        },
        {
          title: "SQ-TableStand",
          paragraph:
            "Carenuity SQ-Table Stand is a mobile table stand that lets the SQ-Panel operate anywhere without wall mounting. It provides a stable, rubber-base platform and USB-C power connection.",
          button: "Explore SQ-TableStand",
        },
        {
          title: "SQ-Connector",
          paragraph:
            "Carenuity SQ-Connector is the central gateway that links SQ-Panels to your local network and cloud, using reliable 868 MHz wireless communication and LAN connectivity.",
          button: "Explore SQ-Connector",
        },
      ],
    },
    about: {
      pageName: "About Page",
      pageDesc:
        "Learn about Carenuity and our mission to deliver intelligent indoor monitoring solutions for healthier living.",
      s1Title: "Crafted for Smart Homes, Health & Business.",
      s1Desc:
        "Carenuity was founded to make indoor air quality monitoring accessible and actionable for everyone — from families at home to professionals in demanding environments.",
      s1List: [
        "Premium quality sensors",
        "Tailwind CSS UI",
        "Use for lifetime",
        "Next.js powered",
        "Rich documentation",
        "Developer friendly",
      ],
      s2Items: [
        {
          title: "Advanced Sensing Technology",
          desc: "Our SQ-Panel uses cutting-edge sensors to measure CO₂, TVOC, temperature, humidity, pressure, and presence — all in one compact device.",
        },
        {
          title: "Privacy-first Architecture",
          desc: "Data stays local by default. We never sell your data, and our system is designed with privacy-friendly principles from the ground up.",
        },
        {
          title: "Award-winning Innovation",
          desc: "Recognized with the BSFZ Seal 2025 for Research & Development by the Federal Republic of Germany — a mark of certified innovation.",
        },
      ],
    },
    blog: {
      pageName: "Blog",
      pageDesc: "News, insights, and updates from the Carenuity team.",
      title: "Our Latest Articles",
      posts: [
        {
          id: 1,
          title: "Best UI components for modern websites",
          excerpt:
            "Discover the most impactful UI patterns for building clean, conversion-focused modern websites.",
          tag: "Design",
          date: "Jan 2025",
          readTime: "5 min read",
        },
        {
          id: 2,
          title: "9 simple ways to improve your design skills",
          excerpt:
            "Practical tips for designers of all skill levels to sharpen their craft and build stronger visual instincts.",
          tag: "Creative",
          date: "Feb 2025",
          readTime: "4 min read",
        },
        {
          id: 3,
          title: "Tips to quickly improve your coding speed",
          excerpt:
            "Boost your productivity with these battle-tested techniques for writing cleaner, faster code.",
          tag: "Development",
          date: "Mar 2025",
          readTime: "6 min read",
        },
      ],
    },
    contact: {
      pageName: "Contact",
      pageDesc: "Get in touch with us. We'd love to hear from you.",
      title: "Need Help? Open a Ticket",
      subtitle: "Our support team will get back to you ASAP via email.",
      namePlaceholder: "Enter your name",
      emailPlaceholder: "Enter your email",
      messagePlaceholder: "Enter your message",
      submitBtn: "Submit Ticket",
      newsletterTitle: "Don't miss a thing!",
      newsletterDesc:
        "Enter your email to get the latest news, feature updates and offers from Carenuity.",
      newsletterBtn: "Subscribe",
      yourName: "Your Name",
      yourEmail: "Your Email",
      yourMessage: "Your Message",
    },
    signin: {
      title: "Sign in to your account",
      subtitle: "Login to your account for a faster checkout.",
      google: "Sign in with Google",
      github: "Sign in with Github",
      or: "Or, sign in with your email",
      email: "Your Email",
      emailPh: "Enter your Email",
      password: "Your Password",
      passwordPh: "Enter your Password",
      remember: "Keep me signed in",
      forgot: "Forgot Password?",
      btn: "Sign in",
      noAccount: "Don't you have an account?",
      signupLink: "Sign up",
    },
    signup: {
      title: "Create your account",
      subtitle: "It's totally free and super easy",
      google: "Sign up with Google",
      github: "Sign up with Github",
      or: "Or, register with your email",
      name: "Full Name",
      namePh: "Enter your full name",
      email: "Work Email",
      emailPh: "Enter your Email",
      password: "Your Password",
      passwordPh: "Enter your Password",
      agree: "By creating account means you agree to the ",
      terms: "Terms and Conditions",
      and: ", and our ",
      privacy: "Privacy Policy",
      btn: "Sign up",
      hasAccount: "Already using Carenuity?",
      signinLink: "Sign in",
    },
    footer: {
      description:
        "Carenuity delivers modular sensor solutions for monitoring vital signs and indoor air quality. The SQ-Panel provides 24/7 vital and environmental sensing in one smart device.",
      contactTitle: "Contacts",
      city: "Munich",
      newsletterTitle: "Newsletter",
      newsletterText:
        "Subscribe to our newsletter to receive updates on the latest news!",
      subscribe: "Subscribe",
      payment: "Payment & Delivery",
      terms: "Terms & conditions",
      withdrawal: "Right of withdrawal",
      privacy: "Privacy Policy",
      legal: "Legal notice",
      copyright:
        "© 2026 ChipGlobe GmbH — ChipGlobe™ and Carenuity™ are Trademarks of ChipGlobe GmbH",
    },
    budgetFriendly: {
      title: "Budget Friendly Not Only For Students",
      currentPage: "Current page",
      explore: "Explore",
      cards: [
        { title: "C3-Mini™ Applications", desc: "GPIO projects, WLED lighting, custom hardware builds and more." },
        { title: "AI Assisted Solutions", desc: "Camera vision, radar sensing, and autonomous smart systems." },
        { title: "All-for-One Sensor Boxes", desc: "Pre-assembled ready-to-use sensor boxes — plug in and measure." },
        { title: "C3-Mini™ Sensor Selection Box", desc: "A curated starter kit with a variety of compatible sensors." },
      ],
    },
    c3mini: {
      badge: "Budget Friendly IoT",
      heroTitle1: "C3-Mini™ Applications",
      heroTitle2: "Build Anything",
      heroSub: "A mini Wi-Fi & Bluetooth 5 (LE) board based on ESP32-C3FH4. Compatible with MicroPython, Arduino, CircuitPython, and ESP-IDF.",
      heroBtn: "C3-Mini™ Applications",
      whatTitle: "What is C3-Mini™?",
      whatP1: "The C3-Mini™ is a compact, powerful microcontroller board based on the ESP32-C3 chip with a RISC-V Single-Core CPU running at 160 MHz. It features Wi-Fi and Bluetooth LE 5.0, a Type-C USB connector, 4 MB of Flash, and 12 GPIO pins with ADC, I2C, SPI, and UART interfaces.",
      whatP2: "It shares the same footprint and pinout as the popular D1 Mini, making it compatible with the world's largest sensor and actuator shield portfolio. The default firmware is MicroPython, but it also supports Arduino, CircuitPython, and ESP-IDF.",
      whatTip: "Tip: To flash the C3-Mini, hold the BOOT button, click the RST button briefly while keeping BOOT pressed, then start WebFlashing.",
      specsTitle: "Technical Specifications",
      specHeaders: ["Specification", "Value"],
      specs: [["Operating Voltage", "3.3V"], ["Digital I/O Pins", "12"], ["Clock Speed", "160 MHz"], ["Flash", "4 MB"], ["Size", "34.3 × 25.4 mm"], ["Weight", "2.6 g"]],
      versionsTitle: "Versions",
      versions: [{ label: "V2.2.1", desc: "Carenuity EU version" }, { label: "V2.1.0", desc: "Lolin version" }, { label: "V1.0.0", desc: "Original version" }],
      hwFeaturesTitle: "Hardware Features",
      hwFeatures: ["ESP32-C3 Wi-Fi & Bluetooth LE with RISC-V Single-Core CPU", "Type-C USB connectivity", "1× WS2812B RGB LED on-board", "ADC, I2C, SPI, UART interfaces", "Compatible with LOLIN D1 Mini shields", "Supports MicroPython, Arduino, CircuitPython, ESP-IDF"],
      buildTitle: "Build your own device within seconds:",
      standaloneApps: [
        { title: "WLED Lighting Control", desc: "Run WLED firmware to control addressable LED strips with effects, music reactivity, and smart home integration.", href: "https://chipglobe-dev.web.app/cloudfree/WLED/C3-Mini" },
        { title: "GPIO Viewer", desc: "Monitor all GPIO pins live in your browser — ideal for debugging hardware projects and sensor circuits.", href: "https://chipglobe-dev.web.app/cloudfree/GPIO/C3-Mini" },
        { title: "YouTube Counter", desc: "Display real-time YouTube channel statistics — subscribers and likes — on a small OLED screen.", href: "https://chipglobe-dev.web.app/cloudfree/YOUTUBE-METEER/C3-Mini" },
      ],
      sensorDevices: [
        { title: "Barometer", desc: "Measure atmospheric pressure and altitude." },
        { title: "Hygrometer", desc: "Track relative humidity and temperature." },
        { title: "Thermometer", desc: "Precise ambient temperature sensing." },
        { title: "Luxmeter", desc: "Measure ambient light intensity in lux." },
        { title: "IR Radiometer", desc: "Non-contact infrared temperature measurement." },
        { title: "Motion Detector", desc: "PIR-based motion detection for automations." },
        { title: "Presence Button", desc: "Capacitive or tactile user interaction input." },
      ],
      tutorialsTitle: "Tutorials",
      tutorialsSub: "Get started with the C3-Mini™ using our step-by-step video tutorial covering MicroPython initialisation and WebFlashing.",
      tutorialsSubTitle: "Getting Started with C3-Mini™",
      tutorialsSubDesc: "Learn how to initialise your C3-Mini™ with MicroPython using WebFlashing — no special tools required.",
      tutorialsSteps: ["Flashing MicroPython via WebFlasher", "Arduino IDE setup and first sketch", "CircuitPython installation guide", "Using ESP-IDF for advanced development", "Compatible with LOLIN D1 Mini shields and accessories"],
      d1Title: "What is the difference between the D1 and the C3-Mini™?",
      d1P1: "The two super popular boards — the D1 and C3-Mini™ — share the same footprint and pinout, making them a perfect fit for the world's largest sensor and actuator portfolio.",
      d1P2: "The C3-Mini™ is the successor to the ESP32-Mini, adding Bluetooth LE 5.0 and future-proofing your projects with support for the upcoming Matter standard.",
      docsTitle: "Documentation",
      docs: [
        { name: "C3-Mini Datasheet V2.2.1 [PDF]", href: "/docs/c3-mini/datasheet-v2.2.1.pdf" },
        { name: "Getting Started with MicroPython [PDF]", href: "/docs/c3-mini/getting-started-micropython.pdf" },
        { name: "Getting Started with Arduino [PDF]", href: "/docs/c3-mini/getting-started-arduino.pdf" },
        { name: "Getting Started with CircuitPython [PDF]", href: "/docs/c3-mini/getting-started-circuitpython.pdf" },
        { name: "C3-Mini Pinout Reference [PDF]", href: "/docs/c3-mini/pinout-reference.pdf" },
        { name: "ESP-IDF Setup Guide [PDF]", href: "/docs/c3-mini/espidf-setup.pdf" },
      ],
      docsBtn: "Explore C3-Mini™ Applications →",
    },
    c3miniApps: {
      badge: "C3-Mini™ Applications",
      heroTitle1: "Build your own device",
      heroTitle2: "within seconds",
      heroSub: "The C3-Mini™ supports install-for-free applications for CloudFree, Home Assistant, IoT AppStore and Matter/ESPZero.",
      section1Title: "Applications for the plain C3-Mini™ — no Display or Sensor required",
      section1Pre: "Grab your plain C3-Mini and build your own device within 3 minutes, by installing the popular ",
      section1WledLink: "WLED-Application",
      section1Mid: ", the helpful ",
      section1GpioLink: "GPIO-Viewer",
      section1Post: ' or a plain "empty" ESPHome device for Home Assistant with no special features built-in. Ready to make it your own.',
      section2Title: "Applications for the C3-Mini™ with Display",
      section2Pre: "Grab your C3-Mini and build your own device within 3 minutes, by attaching a display ",
      section2BuyHere: "buy here",
      section2Mid: " to enable applications like a WiFi Signal Strength Meter, a Weather-Station or a ",
      section2YtLink: "YouTube-Counter",
      section2Post: " for Followers and Likes.",
      section3Title: "Applications for the C3-Mini™ with Sensor & Display",
      section3Desc: "Grab your C3-Mini and build your own device within 3 minutes, by free-installing various sensor applications like a Barometer, Hygrometer, Luxmeter or Motion Detector.",
      backBtn: "Back to C3-Mini Overview",
    },
    c3miniBoxDevices: {
      badge: "C3-Mini Sensor Box",
      heroTitle1: "C3-Mini Sensor Box",
      heroTitle2: "Devices",
      heroSub: "Get the box so that you can build all these C3-Mini Devices within 3 minutes.",
      breadcrumbBox: "C3-Mini Sensor Selection Box",
      breadcrumbCurrent: "C3-Mini Sensor Box Devices",
      introTitle: "Get the box so that you can build all these C3-Mini Devices within 3 minutes.",
      introDesc: "Select your S-M-A Triple, grab the available parts from your drawer or go shopping for getting more suited sensor boxes.",
      cards: [
        { title: "Step 1 — Select your S-M-A Triple", desc: "Choose a Sensor, place the C3-Mini in the middle of the Triple-Adapter, and add a Display or Buzzer as your Actuator." },
        { title: "Step 2 — Install for Free", desc: "Use the Install-for-Free feature to flash your chosen application directly onto the C3-Mini — no coding required." },
        { title: "Step 3 — Your Device is Ready", desc: "Within 3 minutes your sensor device is up and running — reporting live data to CloudFree, Home Assistant, IoT AppStore or Matter." },
      ],
      appsTitle: "Applications",
      appsDesc: "Stack one of the seven sensor boards onto the Triple-Adapter, place the C3-Mini in the middle and add the display or buzzer on the right.",
      assemble: "See how to assemble",
      install: "How to install",
      installVideoTitle: "Installing the App on C3-Mini",
      devices: [
        { title: "Barometer", desc: "Measures atmospheric pressure. It can be equipped with a display to show pressure readings or a buzzer to signal significant changes, which may indicate weather shifts." },
        { title: "Hygrometer", desc: "Monitors air humidity. It may use a display to show relative humidity or a buzzer to alert when humidity levels fall outside a desired range." },
        { title: "IR Radiometer", desc: "Detects thermal radiation without contact. It can use a display to show surface temperatures or a buzzer to indicate abnormal thermal readings." },
        { title: "Luxmeter", desc: "Measures light intensity. It may have a display showing lux values or a buzzer that activates when light levels are too high or too low." },
        { title: "Thermometer", desc: "Measures temperature. It can feature a display for real-time temperature readings or a buzzer to notify when temperatures exceed or drop below set thresholds." },
        { title: "Motion Detector", desc: "Senses movement. It may show motion status on a display or use a buzzer to audibly alert when movement is detected." },
        { title: "Presence Button", desc: "Detects user presence through interaction. It can confirm activation via a display or provide feedback through a buzzer when pressed." },
      ],
    },
    aiAssisted: {
      badge: "AI Assisted Solutions",
      heroTitle1: "AI-Assisted Devices",
      heroTitle2: "at your Fingertip",
      heroSub: "AI-assisted Carenuity devices combine cutting edge sensor technology with artificial intelligence to gather, process, and analyze data from their environment.",
      featuredTitle: "AI-assisted devices",
      featuredDesc: "These sensors detect various physical parameters including temperature, motion, and light, applying AI to make informed decisions based on gathered data.",
      radarTitle: "C3-Mini Radar Sensor",
      radarSubtitle: "Your Radar Occupancy Sensor for Smart Home",
      radarP1: "A radar sensor employs radio waves to detect stationary, approaching, departing or missing objects and measure their distance, speed, and other characteristics through area segmentation.",
      radarP2: "Unlike conventional PIR sensors that rely on heat signatures and struggle with subtle motion or presence detection, the Carenuity™ SQ-Panel features a highly precise 60 GHz radar sensor. This advanced sensing technology enables real-time detection of micro-movements, even through materials, making it suitable for modern presence automation. Whether designing intelligent HVAC or lighting control or building a Home Assistant setup, the Carenuity™ SQ-Panel provides accurate occupancy data via MQTT and seamlessly integrates into smart ecosystems.",
      readMore: "Read more",
      blogCards: [
        { title: "A Beginner's Guide to HLK-LD2410C 24GHz Radar Sensor", excerpt: "Explores the HLK-LD2410, a 24GHz Human Presence sensor." },
        { title: "Discovering the LD2410C Radar Sensor", excerpt: "Covers detection capabilities through walls, fog, and darkness." },
        { title: "Using the BGT60LTR11 Radar Shield2Go with ESP32 for AI Applications", excerpt: "Discusses the compact BGT60LTR11 Radar Shield2Go." },
      ],
      espTitle: "C3-Mini Adapter with ESP32-Cam",
      espP1: "The ESP32-CAM is a compact, low-cost module that combines an ESP32-S microcontroller with an OV2640 camera. In object detection applications, it proves particularly valuable due to built-in Wi-Fi and Bluetooth capabilities, enabling wireless image transmission and processing.",
      espP2: "Leveraging libraries like OpenCV and machine learning models, the ESP32-CAM performs real-time object detection and identification. This makes it ideal for home automation, security systems, and IoT projects requiring visual data capture and analysis.",
      espBlogCard: { title: "Turning Your ESP32-CAM into a Smart Object Detector with Edge Impulse", excerpt: "Tutorial on creating object detection models on ESP32-CAM using Edge Impulse." },
      autoCarTitle: "Autonomous Driving Car",
      autoCarP1: "In the world of automotive innovation, history often serves as a foundation for future advancements. The Autonomous Driving Infineon Car, built by ChipGlobe's Carenuity team, is a testament to this principle.",
      autoCarP2: "This vehicle embodies the latest autonomous driving technology while honoring the legendary Schaeffler FAG Model MF3, unveiled in June 2009. The shark-like design of the MF3, symbolizing speed and precision, has been reincarnated in 2025 in a 1:10 ratio model, showcasing the blend of past and present engineering achievements.",
      autoCarP3: "The Schaeffler FAG Model MF3 unveiling occurred at an evening event at Schaeffler's foyer, attended by Dr. Grunau, former representative of the FAG Schaeffler Group Industry management board, and Dipl.-Ing. Seubert, former chairman of the Unterfranken district association of the Verein Deutscher Ingenieure (VDI).",
      learnMore: "Learn more",
    },
    selectionBox: {
      badge: "Modular Sensor Kit",
      heroTitle1: "C3-Mini™",
      heroTitle2: "Sensor Selection Box",
      heroSub: "Seven featured sensors in one convenient box — everything you need to start building environmental and interactive IoT projects.",
      breadcrumb: "Sensor Selection Box",
      whatTitle: "What is the Sensor Selection Box?",
      whatP1: "The C3-Mini™ Sensor Selection Box is a modular starter kit designed for students, makers, and developers who want to explore a range of IoT sensor types without sourcing components individually.",
      whatP2: "Each box includes seven sensors compatible with the C3-Mini™ board, along with example code and documentation to get you started fast. Swap sensors in and out to build exactly the project you have in mind.",
      installBtn: "Install For Free (14 Devices)",
      sensorsTitle: "Build your own device within 3 minutes:",
      sensorsDesc: "The selection box includes one of each sensor below — a complete toolkit for environmental sensing and interaction projects.",
      sensors: [
        { title: "Barometer", desc: "Measure atmospheric pressure and altitude. Ideal for weather stations and altitude-aware applications." },
        { title: "Hygrometer", desc: "Track relative humidity levels to monitor indoor comfort, condensation risk, and dew point." },
        { title: "Thermometer", desc: "Precise temperature sensing for climate control, cold-chain monitoring, and environmental logging." },
        { title: "Luxmeter", desc: "Measure ambient light intensity in lux to automate lighting or protect photosensitive environments." },
        { title: "IR Radiometer", desc: "Detect infrared radiation for non-contact temperature measurement and remote sensing applications." },
        { title: "Motion Detector", desc: "PIR-based motion detection to trigger alerts, automations, or energy-saving presence logic." },
        { title: "Presence Button", desc: "A capacitive or tactile input for manual presence confirmation or user interaction in your projects." },
      ],
    },
    sensorBoxes: {
      badge: "Single Sensor Box",
      heroTitle1: "Build your own device",
      heroTitle2: "within 3 minutes.",
      heroSub: "Single Sensor Boxes contain all you need to build your own device within 3 minutes. Build devices like a Barometer, Hygrometer, Luxmeter or a Motion Detector.",
      breadcrumb: "All-for-One Sensor Boxes",
      whatTitle: "What is a Sensor Box?",
      whatP1: "Each Single Sensor Box comes in an Acrylic Box, which includes a Triple-Adapter, three stackable boards (S-M-A), a 3D-printed enclosure and a USB Type-C cable to power it.",
      whatP2: "The three slots with letters S-M-A stand for Sensor, Microcontroller and Actuator, typically a display. Besides the sensor, the core part is the C3-Mini microcontroller.",
      whatP3: "The plastic casing, a 3D-printed enclosure, houses all the electronics. You can also print yourself enclosures in your preferred color and customized style. Find our free 3D-models on Thingiverse.",
      whatP4: "The Triple-Adapter makes it a breeze connecting the three boards — sensor, microcontroller and actuator — and you can even build new combinations of S-M-A by this base board, using the IoT Triple Selector of the Solution Builder.",
      whatP5: "All Sensor Boxes contain an actuator (display, buzzer or LED) to make the sensor measurements readable or to trigger acoustic or optical alarms.",
      whatP6: "The USB Type-C data cable finally allows to inject a certain software (install-for-free from a browser window) and later on powering your built device at any location, e.g. by a phone charger.",
      healthcareTitle: "Healthcare Assisting Devices",
      healthcareCards: [
        { title: "Air-Quality-Meter", desc: "Air Quality (VOCs, CO2 & Humidity)" },
        { title: "Bio-Pulse Meter", desc: "Monitor heart rate and biometric data with the C3-Mini™ powered pulse sensor." },
      ],
      motionTitle: "Motion Detection Devices",
      motionCards: [{ title: "Fridge Openings Counter", desc: "Track how many times your fridge is opened using a PIR motion sensor and OLED display." }],
      weatherTitle: "Weather Station Devices",
      weatherCard: { title: "EnviroSense 680", desc: "Advanced Environmental Monitoring Solution — temperature, humidity, pressure, and air quality in one device.", link: "Click here to learn more on EnviroSence 680" },
      installBtn: "Install For Free",
      buyBtn: "Buy C3-Mini Parts",
    },
    installForFree: {
      detailTitle: "How to build your own device",
      badge: "Install For Free",
      heroTitle1: "Build your own device within 3 minutes",
      heroTitle2: "to immediately sense what's going on.",
      heroCta: "Select your S-M-A Triple, grab the available parts from your drawer or go shopping for getting more suited sensor boxes.",
      step1Title: "Make Your Triple",
      step1Desc: "Make your S-M-A Triple by attaching the three basic components of any IoT solution — the Sensor, the Microcontroller and the Actuator — onto the black Triple-Adapter.",
      step2Title: "Install Software",
      step2Desc: "Inject an application from the Solution Builder website into your Triple using any browser on your laptop or PC. No extra PC-software installation is required.",
      step3Title: "Deploy",
      step3Desc: "House your Triple in a 3D-printed enclosure (optional) and place it in your apartment, powered by a phone charger. No PC required.",
      hwTitle: "Get Hardware",
      hwDesc: "As all these boards are super popular, we assume you have them at your hand. If not, check out our free offer below or refill your drawers.",
      hwLink: "Visit our Shop",
      swTitle: "Install Software",
      swDesc1: "For building your own device within 3 minutes, you can select from a wide range of sensors to build your own device — e.g. a Barometer, Hygrometer, Thermometer, Luxmeter, IR Radiometer, Motion Detector or a Presence Button.",
      swDesc2: "Simply use the Install-For-Free App directly from your browser to seamlessly transition between different types of devices. No software installation on your PC is required.",
      swLink: "Open Install-For-Free App",
      sensorLink: "Select Sensor",
      housingTitle: "Housing",
      housingDesc1: "Discover the joy of perfect customization and unlock your creative potential — e.g. by housing the electronics you have built, to give them to your beloved.",
      housingDesc2: "You can do this in various ways, e.g. by a handmade card paper enclosure or a 3D-print.",
      housingLink: "Browse 3D-Print Enclosures",
      smaTitle: "S-M-A Components",
      smaDesc: "For your orientation, we have simplified the stacking by labelling the slots S, M and A on the Triple-Adapter. This makes it as simple as possible to attach the three boards.",
      ecosystemTitle: "Four Ecosystem Options",
      ecosystemDesc: "Choose the smart home ecosystem that best fits your needs.",
      ecosystems: [
        { title: "Cloudfree", desc: "The most secure and simple device does not relate to the internet at all. You install it and it just works. Best if you do not need features beyond the major task of sensing something." },
        { title: "Home Assistant", desc: "Home Assistant specifies in detail which actions are to be taken if a device senses a certain situation. HA is currently the world's most popular environment for smart home devices." },
        { title: "IoT AppStore", desc: "If you have more devices which you want to jointly orchestrate with over-the-air updates, possibly at remote locations (e.g. at your parents' home), the IoT solution is your first choice." },
        { title: "Matter", desc: "Matter allows you to integrate your sensor device with up to five of the most popular platforms at once — Amazon Alexa, Apple Home, Google Home, Samsung SmartThings, or Home Assistant." },
      ],
      statsTitle: "Unlock your success with our smart modular approach today!",
      stats: [
        { value: "28", label: "Sensors" },
        { value: "5", label: "Microcontrollers" },
        { value: "12", label: "Actuators" },
        { value: "1500", label: "Solutions" },
      ],
      greenTitle: "Green Modularity",
      greenDesc1: "At the heart of our innovation lies Green Modularity — a groundbreaking concept that combines Sensors, Microcontrollers, and Actuators (S-, M- & A-boards) as distinct, replaceable parts following the systematic of any IoT product.",
      greenDesc2: "This approach promotes environmental sustainability by reducing electronic waste. By enabling individual component replacement rather than full device disposal, we extend the lifecycle of our products and support a circular economy.",
      weeeTitle: "WEEE Compliance",
      weeeDesc1: "As part of our commitment to sustainability, we fully comply with the Waste Electrical and Electronic Equipment (WEEE) Directive. This ensures the proper collection, recycling, and disposal of electronic products to minimize their environmental impact.",
      weeeDesc2: "Each of our products bears the crossed-out wheeled bin symbol, signaling that it must not be discarded with household waste but instead recycled responsibly.",
      weeeDesc3: "As space is limited on PCBs, we facilitate direct access to this Sustainability website with our WEEE details via the QR-code printed on all our PCBs.",
      weeeNumber: "WEEE Registration Number:",
      weeeCompany: "Carenuity acting as Chipglobe GmbH, Cincinnatistrasse 60, 81549 Munich, Germany",
      weeeContact: "info@chipglobe.com or (+49) 89-1222469-40",
      greenClose: "By integrating Green Modularity into our product designs and adhering to strict compliance protocols, we ensure that sustainability is not just a promise, but a practice. Join the movement toward a smarter, greener planet.",
    },
  },
  de: {
    nav: {
      home: "START",
      product: "PRODUKT",
      benefits: "VORTEILE",
      resources: "RESSOURCEN",
      install: "Kostenlos installieren",
      signin: "Anmelden",
      signup: "Registrieren",
    },
    breadcrumb: { home: "Startseite" },
    hero: {
      line1: "Gesund, komfortabel,",
      line2: "und vernetzt",
      sub1: "Überwachen Sie Luftqualität, Anwesenheit und mehr jederzeit,",
      sub2: "überall über die Carenuity-App.",
    },
    home: {
      aboutTitle: "Über uns",
      aboutDesc:
        "Carenuity ist eine intelligente Innenraum-Überwachungslösung, die Häuser und Angehörige sicher, komfortabel und gut belüftet hält. Angetrieben von fortschrittlichen Umgebungssensoren verfolgt das System in Echtzeit Luftqualität, Temperatur, Luftfeuchtigkeit, Druck, CO₂, TVOC und Anwesenheit.",
      aboutBtn: "Mehr über uns erfahren",
      productsTitle: "Produktlinien",
      productsDesc:
        "Flexible Lösungen für verschiedene Anforderungen — von Premium-Langzeitsystemen bis hin zu budgetfreundlichen Einstiegsprodukten.",
      whyTitle: "Warum Carenuity",
      whyDesc:
        "Carenuity ermöglicht es Ihnen, Ihre Wohnumgebung zu überwachen und zu verbessern und dabei Komfort, Sicherheit und Wohlbefinden für Ihre Angehörigen zu gewährleisten.",
      awardTitle: "Auszeichnung",
      awardDesc:
        "Ausgezeichnet mit dem BSFZ-Siegel 2025 für Forschung & Entwicklung",
      awardBody:
        "Das rote BSFZ-Siegel, verliehen von der Bundesrepublik Deutschland, bescheinigt, dass Carenuity eigene Forschung und Entwicklung betreibt. Das SQ-Panel ist offiziell als Ergebnis innovativer F&E anerkannt.",
      exploreSystem: "SQ-System erkunden",
      exploreC3: "C3-Mini-Produkte erkunden",
      products: [
        {
          title: "SQ-System",
          paragraph:
            "Ein modulares Premium-System für professionelles Luftqualitätsmonitoring. Entwickelt für dauerhafte Installationen, skalierbare Umgebungen und langfristigen Einsatz.",
          list: [
            "Modular & erweiterbar",
            "Saubere, diskrete Installation",
            "Datenschutzfreundlich",
          ],
        },
        {
          title: "Hochwertige Designs",
          paragraph:
            "Erschwingliche Einstiegslösungen, die softwaregesteuert und flexibel sind. Ideal für Studenten, Startups und Entwickler.",
          list: [
            "Erschwingliche Einstiegslösungen",
            "Softwaregesteuert & flexibel",
            "Ideal für Studenten & Entwickler",
          ],
        },
      ],
      whyItems: [
        {
          title: "Zuhause & Familie",
          paragraph: "Gesunde Innenraumluft für den täglichen Alltag",
        },
        {
          title: "Büros & Unternehmen",
          paragraph: "Bessere Luftqualität für Produktivität und Wohlbefinden",
        },
        {
          title: "Pflege & Gesundheit",
          paragraph: "Zuverlässige Überwachung für sensible Umgebungen",
        },
        {
          title: "Schulen & Bildung",
          paragraph:
            "Modulare Lösungen für sichere, intelligente Lernumgebungen.",
        },
        {
          title: "Home Challenge",
          paragraph:
            "Die Carenuity Home Challenge ermöglicht es Ihnen, Smart-Home-Geräte zu bauen und IoT-Kenntnisse zu erwerben.",
        },
      ],
    },
    testimonials: {
      title: "Was unsere Nutzer sagen",
      items: [
        {
          name: "Patrick",
          content:
            "Ich verlasse mich auf das Carenuity SQ-Panel, um die Luftqualität zu verfolgen. Die historischen Daten sind wertvoll für eine sicherere Wohnumgebung.",
          star: 5,
        },
        {
          name: "Patricia",
          content:
            "Das Carenuity SQ-Panel hat die Überwachung der Luftqualität einfach und effektiv gemacht. Die Echtzeit-Benachrichtigungen der App geben mir Sicherheit.",
          star: 5,
        },
      ],
    },
    sqSystem: {
      heading: "SQ-System",
      description:
        "Das Carenuity SQ-System ist eine modulare Innenraumüberwachungslösung, bestehend aus SQ-Panel, SQ-Power, SQ-Connector und SQ-Table Stand. Das SQ-Panel beherbergt fortschrittliche Umgebungssensoren, die kontinuierlich Luftqualität, Temperatur, Luftfeuchtigkeit, Druck, CO₂, TVOC und Anwesenheit messen.",
      videoTitle: "Videos zum SQ-Panel und SQ-Power",
      sqPanel: "SQ-Panel",
      sqPower: "SQ-Power",
      products: [
        {
          title: "SQ-Panel",
          paragraph:
            "Das Carenuity SQ-Panel überwacht Luftqualität, Temperatur, Luftfeuchtigkeit, Druck, CO₂, TVOC und Anwesenheit in Echtzeit.",
          button: "SQ-Panel erkunden",
        },
        {
          title: "SQ-Power",
          paragraph:
            "Das Carenuity SQ-Power ist ein kompaktes Unterputz-Netzteilmodul, das dem SQ-Panel eine stabile 5-V-Gleichspannung liefert.",
          button: "SQ-Power erkunden",
        },
        {
          title: "SQ-TableStand",
          paragraph:
            "Der Carenuity SQ-Tischständer ist ein mobiler Tischständer, mit dem das SQ-Panel ohne Wandmontage überall betrieben werden kann.",
          button: "SQ-TableStand erkunden",
        },
        {
          title: "SQ-Connector",
          paragraph:
            "Der Carenuity SQ-Connector ist das zentrale Gateway, das SQ-Panels über 868-MHz-Drahtloskommunikation mit Ihrem Netzwerk und der Cloud verbindet.",
          button: "SQ-Connector erkunden",
        },
      ],
    },
    about: {
      pageName: "Über uns",
      pageDesc:
        "Erfahren Sie mehr über Carenuity und unsere Mission, intelligente Innenraum-Überwachungslösungen zu liefern.",
      s1Title: "Entwickelt für Smart Homes, Gesundheit & Unternehmen.",
      s1Desc:
        "Carenuity wurde gegründet, um die Überwachung der Innenraumluftqualität für alle zugänglich und umsetzbar zu machen.",
      s1List: [
        "Hochwertige Sensoren",
        "Tailwind CSS UI",
        "Lebenslang nutzbar",
        "Next.js-basiert",
        "Umfangreiche Dokumentation",
        "Entwicklerfreundlich",
      ],
      s2Items: [
        {
          title: "Fortschrittliche Sensortechnologie",
          desc: "Unser SQ-Panel verwendet Hochleistungssensoren zur Messung von CO₂, TVOC, Temperatur, Luftfeuchtigkeit, Druck und Anwesenheit.",
        },
        {
          title: "Datenschutz-Architektur",
          desc: "Daten bleiben standardmäßig lokal. Wir verkaufen Ihre Daten nie und unser System ist von Grund auf datenschutzfreundlich.",
        },
        {
          title: "Preisgekrönte Innovation",
          desc: "Ausgezeichnet mit dem BSFZ-Siegel 2025 für Forschung & Entwicklung — ein Zeichen zertifizierter Innovation.",
        },
      ],
    },
    blog: {
      pageName: "Blog",
      pageDesc: "Neuigkeiten, Einblicke und Updates vom Carenuity-Team.",
      title: "Unsere neuesten Artikel",
      posts: [
        {
          id: 1,
          title: "Beste UI-Komponenten für moderne Websites",
          excerpt:
            "Entdecken Sie die wirkungsvollsten UI-Muster für moderne Websites.",
          tag: "Design",
          date: "Jan 2025",
          readTime: "5 Min.",
        },
        {
          id: 2,
          title: "9 einfache Wege zur Verbesserung Ihrer Design-Fähigkeiten",
          excerpt: "Praktische Tipps für Designer aller Erfahrungsstufen.",
          tag: "Kreativ",
          date: "Feb 2025",
          readTime: "4 Min.",
        },
        {
          id: 3,
          title: "Tipps zur Verbesserung Ihrer Coding-Geschwindigkeit",
          excerpt:
            "Steigern Sie Ihre Produktivität mit diesen bewährten Techniken.",
          tag: "Entwicklung",
          date: "Mär 2025",
          readTime: "6 Min.",
        },
      ],
    },
    contact: {
      pageName: "Kontakt",
      pageDesc:
        "Nehmen Sie Kontakt mit uns auf. Wir freuen uns auf Ihre Nachricht.",
      title: "Hilfe benötigt? Ticket erstellen",
      subtitle: "Unser Support-Team meldet sich schnellstmöglich per E-Mail.",
      namePlaceholder: "Ihren Namen eingeben",
      emailPlaceholder: "E-Mail eingeben",
      messagePlaceholder: "Ihre Nachricht eingeben",
      submitBtn: "Ticket senden",
      newsletterTitle: "Nichts verpassen!",
      newsletterDesc:
        "Geben Sie Ihre E-Mail ein, um die neuesten Nachrichten und Angebote von Carenuity zu erhalten.",
      newsletterBtn: "Abonnieren",
      yourName: "Ihr Name",
      yourEmail: "Ihre E-Mail",
      yourMessage: "Ihre Nachricht",
    },
    signin: {
      title: "In Ihr Konto einloggen",
      subtitle: "Melden Sie sich für einen schnelleren Checkout an.",
      google: "Mit Google anmelden",
      github: "Mit Github anmelden",
      or: "Oder mit Ihrer E-Mail anmelden",
      email: "Ihre E-Mail",
      emailPh: "E-Mail eingeben",
      password: "Ihr Passwort",
      passwordPh: "Passwort eingeben",
      remember: "Angemeldet bleiben",
      forgot: "Passwort vergessen?",
      btn: "Anmelden",
      noAccount: "Noch kein Konto?",
      signupLink: "Registrieren",
    },
    signup: {
      title: "Konto erstellen",
      subtitle: "Völlig kostenlos und super einfach",
      google: "Mit Google registrieren",
      github: "Mit Github registrieren",
      or: "Oder mit Ihrer E-Mail registrieren",
      name: "Vollständiger Name",
      namePh: "Vollständigen Namen eingeben",
      email: "Geschäftliche E-Mail",
      emailPh: "E-Mail eingeben",
      password: "Ihr Passwort",
      passwordPh: "Passwort eingeben",
      agree: "Durch die Kontoerstellung stimmen Sie den ",
      terms: "Nutzungsbedingungen",
      and: " und unserer ",
      privacy: "Datenschutzrichtlinie",
      btn: "Registrieren",
      hasAccount: "Bereits bei Carenuity?",
      signinLink: "Anmelden",
    },
    footer: {
      description:
        "Carenuity liefert modulare Sensorlösungen zur Überwachung von Vitalzeichen und Innenraumluftqualität. Das SQ-Panel bietet 24/7 Erfassung in einem smarten Gerät.",
      contactTitle: "Kontakt",
      city: "München",
      newsletterTitle: "Newsletter",
      newsletterText:
        "Abonnieren Sie unseren Newsletter für die neuesten Nachrichten!",
      subscribe: "Abonnieren",
      payment: "Zahlung & Lieferung",
      terms: "AGB",
      withdrawal: "Widerrufsrecht",
      privacy: "Datenschutz",
      legal: "Impressum",
      copyright:
        "© 2026 ChipGlobe GmbH — ChipGlobe™ und Carenuity™ sind Marken der ChipGlobe GmbH",
    },
    budgetFriendly: {
      title: "Budgetfreundlich – nicht nur für Studenten",
      currentPage: "Aktuelle Seite",
      explore: "Entdecken",
      cards: [
        { title: "C3-Mini™ Anwendungen", desc: "GPIO-Projekte, WLED-Beleuchtung, individuelle Hardware-Projekte und mehr." },
        { title: "KI-gestützte Lösungen", desc: "Kameravision, Radarsensoren und autonome Smart-Systeme." },
        { title: "All-in-One-Sensorboxen", desc: "Vorinstallierte, einsatzbereite Sensorboxen – einstecken und messen." },
        { title: "C3-Mini™ Sensor-Auswahlbox", desc: "Ein kuratiertes Starterpaket mit einer Auswahl kompatibler Sensoren." },
      ],
    },
    c3mini: {
      badge: "Budgetfreundliches IoT",
      heroTitle1: "C3-Mini™ Anwendungen",
      heroTitle2: "Alles ist möglich",
      heroSub: "Ein kompaktes Wi-Fi- & Bluetooth-5-Board (LE) auf Basis des ESP32-C3FH4. Kompatibel mit MicroPython, Arduino, CircuitPython und ESP-IDF.",
      heroBtn: "C3-Mini™ Anwendungen",
      whatTitle: "Was ist der C3-Mini™?",
      whatP1: "Der C3-Mini™ ist ein kompaktes, leistungsstarkes Mikrocontroller-Board auf Basis des ESP32-C3-Chips mit einer RISC-V Single-Core-CPU mit 160 MHz. Er verfügt über Wi-Fi und Bluetooth LE 5.0, einen Type-C-USB-Anschluss, 4 MB Flash und 12 GPIO-Pins mit ADC-, I2C-, SPI- und UART-Schnittstellen.",
      whatP2: "Er hat denselben Formfaktor und dieselbe Pinbelegung wie der beliebte D1 Mini und ist damit kompatibel mit dem weltweit größten Sensor- und Aktor-Shield-Portfolio. Die Standardfirmware ist MicroPython, aber er unterstützt auch Arduino, CircuitPython und ESP-IDF.",
      whatTip: "Tipp: Zum Flashen des C3-Mini den BOOT-Taster halten, kurz den RST-Taster drücken (BOOT weiter halten) und dann WebFlashing starten.",
      specsTitle: "Technische Daten",
      specHeaders: ["Spezifikation", "Wert"],
      specs: [["Betriebsspannung", "3,3 V"], ["Digitale I/O-Pins", "12"], ["Taktfrequenz", "160 MHz"], ["Flash", "4 MB"], ["Größe", "34,3 × 25,4 mm"], ["Gewicht", "2,6 g"]],
      versionsTitle: "Versionen",
      versions: [{ label: "V2.2.1", desc: "Carenuity EU-Version" }, { label: "V2.1.0", desc: "Lolin-Version" }, { label: "V1.0.0", desc: "Originalversion" }],
      hwFeaturesTitle: "Hardware-Merkmale",
      hwFeatures: ["ESP32-C3 Wi-Fi & Bluetooth LE mit RISC-V Single-Core-CPU", "Type-C-USB-Anschluss", "1× WS2812B RGB-LED an Bord", "ADC-, I2C-, SPI-, UART-Schnittstellen", "Kompatibel mit LOLIN D1 Mini Shields", "Unterstützt MicroPython, Arduino, CircuitPython, ESP-IDF"],
      buildTitle: "Eigenes Gerät in Sekunden bauen:",
      standaloneApps: [
        { title: "WLED Lichtsteuerung", desc: "WLED-Firmware für adressierbare LED-Streifen mit Effekten, Musikreaktivität und Smart-Home-Integration.", href: "https://chipglobe-dev.web.app/cloudfree/WLED/C3-Mini" },
        { title: "GPIO-Viewer", desc: "Alle GPIO-Pins live im Browser überwachen – ideal zum Debuggen von Hardware-Projekten und Sensorschaltungen.", href: "https://chipglobe-dev.web.app/cloudfree/GPIO/C3-Mini" },
        { title: "YouTube-Zähler", desc: "YouTube-Kanalstatistiken – Abonnenten und Likes – in Echtzeit auf einem kleinen OLED-Display anzeigen.", href: "https://chipglobe-dev.web.app/cloudfree/YOUTUBE-METEER/C3-Mini" },
      ],
      sensorDevices: [
        { title: "Barometer", desc: "Atmosphärischen Druck und Höhe messen." },
        { title: "Hygrometer", desc: "Relative Luftfeuchtigkeit und Temperatur erfassen." },
        { title: "Thermometer", desc: "Präzise Umgebungstemperaturmessung." },
        { title: "Luxmeter", desc: "Umgebungslichtintensität in Lux messen." },
        { title: "IR-Radiometer", desc: "Berührungslose Infrarot-Temperaturmessung." },
        { title: "Bewegungsmelder", desc: "PIR-basierte Bewegungserkennung für Automatisierungen." },
        { title: "Anwesenheits-Taster", desc: "Kapazitive oder taktile Benutzereingabe." },
      ],
      tutorialsTitle: "Tutorials",
      tutorialsSub: "Erste Schritte mit dem C3-Mini™ in unserem Schritt-für-Schritt-Video-Tutorial zur MicroPython-Initialisierung und zum WebFlashing.",
      tutorialsSubTitle: "Erste Schritte mit dem C3-Mini™",
      tutorialsSubDesc: "Lernen Sie, wie Sie den C3-Mini™ mit MicroPython über WebFlashing initialisieren – ohne spezielle Werkzeuge.",
      tutorialsSteps: ["MicroPython über WebFlasher flashen", "Arduino-IDE einrichten und erstes Sketch erstellen", "CircuitPython-Installationsanleitung", "ESP-IDF für fortgeschrittene Entwicklung nutzen", "Kompatibel mit LOLIN D1 Mini Shields und Zubehör"],
      d1Title: "Was ist der Unterschied zwischen dem D1 und dem C3-Mini™?",
      d1P1: "Die beiden beliebten Boards – der D1 und der C3-Mini™ – haben denselben Formfaktor und dieselbe Pinbelegung und passen damit perfekt zum weltweit größten Sensor- und Aktorportfolio.",
      d1P2: "Der C3-Mini™ ist der Nachfolger des ESP32-Mini und bietet Bluetooth LE 5.0 sowie Unterstützung für den kommenden Matter-Standard.",
      docsTitle: "Dokumentation",
      docs: [
        { name: "C3-Mini Datenblatt V2.2.1 [PDF]", href: "/docs/c3-mini/datasheet-v2.2.1.pdf" },
        { name: "Erste Schritte mit MicroPython [PDF]", href: "/docs/c3-mini/getting-started-micropython.pdf" },
        { name: "Erste Schritte mit Arduino [PDF]", href: "/docs/c3-mini/getting-started-arduino.pdf" },
        { name: "Erste Schritte mit CircuitPython [PDF]", href: "/docs/c3-mini/getting-started-circuitpython.pdf" },
        { name: "C3-Mini Pinout-Referenz [PDF]", href: "/docs/c3-mini/pinout-reference.pdf" },
        { name: "ESP-IDF Setup-Anleitung [PDF]", href: "/docs/c3-mini/espidf-setup.pdf" },
      ],
      docsBtn: "C3-Mini™ Anwendungen erkunden →",
    },
    c3miniApps: {
      badge: "C3-Mini™ Anwendungen",
      heroTitle1: "Eigenes Gerät bauen",
      heroTitle2: "in Sekunden",
      heroSub: "Der C3-Mini™ unterstützt kostenlose Install-Anwendungen für CloudFree, Home Assistant, IoT AppStore und Matter/ESPZero.",
      section1Title: "Anwendungen für den C3-Mini™ ohne Display oder Sensor",
      section1Pre: "Nehmen Sie Ihren C3-Mini und bauen Sie in 3 Minuten Ihr eigenes Gerät, indem Sie die beliebte ",
      section1WledLink: "WLED-Anwendung",
      section1Mid: ", den hilfreichen ",
      section1GpioLink: "GPIO-Viewer",
      section1Post: " oder ein leeres ESPHome-Gerät für Home Assistant ohne spezielle Funktionen installieren. Bereit für Ihre eigenen Projekte.",
      section2Title: "Anwendungen für den C3-Mini™ mit Display",
      section2Pre: "Nehmen Sie Ihren C3-Mini und bauen Sie in 3 Minuten Ihr eigenes Gerät, indem Sie ein Display ",
      section2BuyHere: "hier kaufen",
      section2Mid: " anschließen, um Anwendungen wie ein WLAN-Signalstärkemessgerät, eine Wetterstation oder einen ",
      section2YtLink: "YouTube-Zähler",
      section2Post: " für Follower und Likes zu aktivieren.",
      section3Title: "Anwendungen für den C3-Mini™ mit Sensor & Display",
      section3Desc: "Nehmen Sie Ihren C3-Mini und bauen Sie in 3 Minuten Ihr eigenes Gerät durch kostenlose Installation von Sensoranwendungen wie Barometer, Hygrometer, Luxmeter oder Bewegungsmelder.",
      backBtn: "Zurück zur C3-Mini-Übersicht",
    },
    c3miniBoxDevices: {
      badge: "C3-Mini Sensor Box",
      heroTitle1: "C3-Mini Sensor Box",
      heroTitle2: "Geräte",
      heroSub: "Holen Sie sich die Box, um alle diese C3-Mini-Geräte innerhalb von 3 Minuten zu bauen.",
      breadcrumbBox: "C3-Mini Sensor-Auswahlbox",
      breadcrumbCurrent: "C3-Mini Sensor Box Geräte",
      introTitle: "Holen Sie sich die Box, um alle diese C3-Mini-Geräte innerhalb von 3 Minuten zu bauen.",
      introDesc: "Wählen Sie Ihr S-M-A-Triple, nehmen Sie die verfügbaren Teile aus Ihrer Schublade oder kaufen Sie passendere Sensorboxen.",
      cards: [
        { title: "Schritt 1 — S-M-A-Triple auswählen", desc: "Wählen Sie einen Sensor, platzieren Sie den C3-Mini in der Mitte des Triple-Adapters und fügen Sie ein Display oder einen Summer als Aktor hinzu." },
        { title: "Schritt 2 — Kostenlos installieren", desc: "Nutzen Sie die Install-for-Free-Funktion, um Ihre gewählte Anwendung direkt auf den C3-Mini zu flashen – kein Programmieren erforderlich." },
        { title: "Schritt 3 — Ihr Gerät ist bereit", desc: "In 3 Minuten ist Ihr Sensorgerät einsatzbereit und überträgt Live-Daten an CloudFree, Home Assistant, IoT AppStore oder Matter." },
      ],
      appsTitle: "Anwendungen",
      appsDesc: "Stapeln Sie eine der sieben Sensorplatinen auf den Triple-Adapter, platzieren Sie den C3-Mini in der Mitte und fügen Sie das Display oder den Summer rechts hinzu.",
      assemble: "Montagevideo ansehen",
      install: "Installationsanleitung",
      installVideoTitle: "App auf den C3-Mini installieren",
      devices: [
        { title: "Barometer", desc: "Misst den Luftdruck. Kann mit einem Display zur Anzeige der Druckwerte oder einem Summer zur Signalisierung erheblicher Änderungen ausgestattet werden." },
        { title: "Hygrometer", desc: "Überwacht die Luftfeuchtigkeit. Kann ein Display zur Anzeige der relativen Feuchtigkeit oder einen Summer zur Warnung bei unerwünschten Feuchtigkeitswerten verwenden." },
        { title: "IR-Radiometer", desc: "Erkennt Wärmestrahlung berührungslos. Kann ein Display für Oberflächentemperaturen oder einen Summer für abnorme Wärmewerte verwenden." },
        { title: "Luxmeter", desc: "Misst die Lichtintensität. Kann ein Display mit Lux-Werten oder einen Summer bei zu hohen oder niedrigen Lichtwerten haben." },
        { title: "Thermometer", desc: "Misst die Temperatur. Kann ein Display für Echtzeit-Temperaturwerte oder einen Summer bei Über- oder Unterschreitung von Schwellenwerten haben." },
        { title: "Bewegungsmelder", desc: "Erkennt Bewegungen. Kann den Bewegungsstatus auf einem Display anzeigen oder einen Summer als akustischen Alarm verwenden." },
        { title: "Anwesenheits-Taster", desc: "Erkennt die Benutzeranwesenheit durch Interaktion. Kann die Aktivierung über ein Display bestätigen oder durch einen Summer Feedback geben." },
      ],
    },
    aiAssisted: {
      badge: "KI-gestützte Lösungen",
      heroTitle1: "KI-gestützte Geräte",
      heroTitle2: "immer griffbereit",
      heroSub: "KI-gestützte Carenuity-Geräte kombinieren modernste Sensortechnologie mit künstlicher Intelligenz, um Daten aus ihrer Umgebung zu erfassen, zu verarbeiten und zu analysieren.",
      featuredTitle: "KI-gestützte Geräte",
      featuredDesc: "Diese Sensoren erfassen verschiedene physikalische Parameter wie Temperatur, Bewegung und Licht und wenden KI an, um fundierte Entscheidungen auf Basis der erfassten Daten zu treffen.",
      radarTitle: "C3-Mini Radarsensor",
      radarSubtitle: "Ihr Radar-Anwesenheitssensor für das Smart Home",
      radarP1: "Ein Radarsensor nutzt Radiowellen, um stationäre, sich nähernde, entfernende oder fehlende Objekte zu erkennen und deren Entfernung, Geschwindigkeit und andere Merkmale durch Flächensegmentierung zu messen.",
      radarP2: "Im Gegensatz zu herkömmlichen PIR-Sensoren, die auf Wärmesignaturen basieren und bei subtilen Bewegungen Schwierigkeiten haben, verfügt das Carenuity™ SQ-Panel über einen hochpräzisen 60-GHz-Radarsensor. Diese Technologie ermöglicht die Echtzeit-Erkennung von Mikrobewegungen, auch durch Materialien hindurch, und eignet sich für moderne Anwesenheitsautomatisierung sowie HVAC- und Beleuchtungssteuerung.",
      readMore: "Weiterlesen",
      blogCards: [
        { title: "Einführung in den HLK-LD2410C 24-GHz-Radarsensor", excerpt: "Erkundet den HLK-LD2410, einen 24-GHz-Personenpräsenzsensor." },
        { title: "Den LD2410C Radarsensor entdecken", excerpt: "Behandelt Erkennungsfähigkeiten durch Wände, Nebel und Dunkelheit." },
        { title: "BGT60LTR11 Radar Shield2Go mit ESP32 für KI-Anwendungen", excerpt: "Behandelt das kompakte BGT60LTR11 Radar Shield2Go." },
      ],
      espTitle: "C3-Mini Adapter mit ESP32-Cam",
      espP1: "Das ESP32-CAM ist ein kompaktes, kostengünstiges Modul, das einen ESP32-S-Mikrocontroller mit einer OV2640-Kamera kombiniert. Bei Objekterkennungsanwendungen erweist es sich durch integriertes Wi-Fi und Bluetooth als besonders wertvoll.",
      espP2: "Durch den Einsatz von Bibliotheken wie OpenCV und Machine-Learning-Modellen führt das ESP32-CAM Echtzeit-Objekterkennung und -identifikation durch. Dies macht es ideal für Heimautomatisierung, Sicherheitssysteme und IoT-Projekte mit visueller Datenerfassung.",
      espBlogCard: { title: "ESP32-CAM mit Edge Impulse in einen smarten Objektdetektor verwandeln", excerpt: "Tutorial zur Erstellung von Objekterkennungsmodellen auf dem ESP32-CAM mit Edge Impulse." },
      autoCarTitle: "Autonomes Fahrzeug",
      autoCarP1: "In der Welt der automobilen Innovation dient die Geschichte oft als Grundlage für zukünftige Entwicklungen. Das Autonome Infineon-Fahrzeug, gebaut vom Carenuity-Team von ChipGlobe, ist ein Beweis für dieses Prinzip.",
      autoCarP2: "Dieses Fahrzeug verkörpert die neueste autonome Fahrtechnologie und ehrt den legendären Schaeffler FAG Model MF3 von 2009. Das haifischförmige Design des MF3, das Geschwindigkeit und Präzision symbolisiert, wurde 2025 im Maßstab 1:10 neu erschaffen.",
      autoCarP3: "Die Präsentation des Schaeffler FAG Model MF3 fand bei einer Abendveranstaltung im Foyer von Schaeffler statt, besucht von Dr. Grunau und Dipl.-Ing. Seubert.",
      learnMore: "Mehr erfahren",
    },
    selectionBox: {
      badge: "Modulares Sensorkit",
      heroTitle1: "C3-Mini™",
      heroTitle2: "Sensor-Auswahlbox",
      heroSub: "Sieben ausgewählte Sensoren in einer praktischen Box – alles, was Sie für den Einstieg in Umgebungs- und interaktive IoT-Projekte benötigen.",
      breadcrumb: "Sensor-Auswahlbox",
      whatTitle: "Was ist die Sensor-Auswahlbox?",
      whatP1: "Die C3-Mini™ Sensor-Auswahlbox ist ein modulares Starterpaket für Studenten, Maker und Entwickler, die eine Reihe von IoT-Sensortypen ausprobieren möchten, ohne Bauteile einzeln beschaffen zu müssen.",
      whatP2: "Jede Box enthält sieben mit dem C3-Mini™-Board kompatible Sensoren sowie Beispielcode und Dokumentation für einen schnellen Einstieg. Tauschen Sie Sensoren aus, um genau das Projekt zu bauen, das Sie im Sinn haben.",
      installBtn: "Kostenlos installieren (14 Geräte)",
      sensorsTitle: "Eigenes Gerät in 3 Minuten bauen:",
      sensorsDesc: "Die Auswahlbox enthält je einen der unten aufgeführten Sensoren – ein vollständiges Toolkit für Umgebungsmess- und Interaktionsprojekte.",
      sensors: [
        { title: "Barometer", desc: "Misst atmosphärischen Druck und Höhe. Ideal für Wetterstationen und höhenbewusste Anwendungen." },
        { title: "Hygrometer", desc: "Überwacht die relative Luftfeuchtigkeit für Innenraumkomfort, Kondensationsrisiko und Taupunkt." },
        { title: "Thermometer", desc: "Präzise Temperaturmessung für Klimasteuerung, Kühlketten-Überwachung und Umgebungsprotokollierung." },
        { title: "Luxmeter", desc: "Misst die Umgebungslichtintensität in Lux zur Beleuchtungsautomatisierung oder zum Schutz lichtempfindlicher Umgebungen." },
        { title: "IR-Radiometer", desc: "Erkennt Infrarotstrahlung für berührungslose Temperaturmessung und Fernerkundungsanwendungen." },
        { title: "Bewegungsmelder", desc: "PIR-basierte Bewegungserkennung zur Auslösung von Alarmen, Automatisierungen oder energiesparender Anwesenheitslogik." },
        { title: "Anwesenheits-Taster", desc: "Kapazitive oder taktile Eingabe zur manuellen Anwesenheitsbestätigung oder Benutzerinteraktion." },
      ],
    },
    sensorBoxes: {
      badge: "Einzelne Sensorbox",
      heroTitle1: "Eigenes Gerät bauen",
      heroTitle2: "in 3 Minuten.",
      heroSub: "Einzelne Sensorboxen enthalten alles, was Sie benötigen, um in 3 Minuten Ihr eigenes Gerät zu bauen – Barometer, Hygrometer, Luxmeter oder Bewegungsmelder.",
      breadcrumb: "All-in-One-Sensorboxen",
      whatTitle: "Was ist eine Sensorbox?",
      whatP1: "Jede einzelne Sensorbox kommt in einer Acrylbox, die einen Triple-Adapter, drei stapelbare Platinen (S-M-A), ein 3D-gedrucktes Gehäuse und ein USB-Type-C-Kabel zur Stromversorgung enthält.",
      whatP2: "Die drei Steckplätze S-M-A stehen für Sensor, Mikrocontroller und Aktor, typischerweise ein Display. Der Kernbestandteil neben dem Sensor ist der C3-Mini-Mikrocontroller.",
      whatP3: "Das Kunststoffgehäuse, ein 3D-gedrucktes Gehäuse, beherbergt die gesamte Elektronik. Sie können auch selbst Gehäuse in Ihrer bevorzugten Farbe und in individuellem Stil drucken. Unsere kostenlosen 3D-Modelle finden Sie auf Thingiverse.",
      whatP4: "Der Triple-Adapter macht das Verbinden der drei Platinen – Sensor, Mikrocontroller und Aktor – zum Kinderspiel, und Sie können sogar neue S-M-A-Kombinationen mit dieser Basisplatine bauen.",
      whatP5: "Alle Sensorboxen enthalten einen Aktor (Display, Summer oder LED), um die Sensormessungen lesbar zu machen oder akustische bzw. optische Alarme auszulösen.",
      whatP6: "Das USB-Type-C-Datenkabel ermöglicht schließlich das Einspielen einer bestimmten Software (Install-for-Free über ein Browserfenster) und später die Stromversorgung des Geräts an einem beliebigen Ort.",
      healthcareTitle: "Medizinische Assistenzgeräte",
      healthcareCards: [
        { title: "Luftqualitätsmessgerät", desc: "Luftqualität (VOCs, CO₂ & Luftfeuchtigkeit)" },
        { title: "Bio-Puls-Messgerät", desc: "Herzfrequenz und biometrische Daten mit dem C3-Mini™-betriebenen Pulssensor überwachen." },
      ],
      motionTitle: "Bewegungserkennungsgeräte",
      motionCards: [{ title: "Kühlschrank-Öffnungszähler", desc: "Zählt mit PIR-Bewegungssensor und OLED-Display, wie oft der Kühlschrank geöffnet wird." }],
      weatherTitle: "Wetterstationsgeräte",
      weatherCard: { title: "EnviroSense 680", desc: "Fortschrittliche Umgebungsüberwachungslösung – Temperatur, Luftfeuchtigkeit, Druck und Luftqualität in einem Gerät.", link: "Hier klicken für mehr Infos zum EnviroSence 680" },
      installBtn: "Kostenlos installieren",
      buyBtn: "C3-Mini-Teile kaufen",
    },
    installForFree: {
      detailTitle: "So bauen Sie Ihr eigenes Gerät",
      badge: "Kostenlos installieren",
      heroTitle1: "Eigenes Gerät in 3 Minuten bauen",
      heroTitle2: "und sofort sehen, was passiert.",
      heroCta: "Wählen Sie Ihr S-M-A-Triple, nehmen Sie die verfügbaren Teile aus Ihrer Schublade oder kaufen Sie passendere Sensorboxen.",
      step1Title: "Ihr Triple zusammenstellen",
      step1Desc: "Stellen Sie Ihr S-M-A-Triple zusammen, indem Sie die drei Grundkomponenten jeder IoT-Lösung — Sensor, Mikrocontroller und Aktor — auf den schwarzen Triple-Adapter stecken.",
      step2Title: "Software installieren",
      step2Desc: "Laden Sie eine Anwendung vom Solution Builder in Ihr Triple — direkt über einen Browser auf Laptop oder PC. Keine zusätzliche PC-Software-Installation erforderlich.",
      step3Title: "In Betrieb nehmen",
      step3Desc: "Setzen Sie Ihr Triple in ein 3D-gedrucktes Gehäuse (optional) und platzieren Sie es in Ihrer Wohnung — mit einem Handyladegerät betrieben. Kein PC notwendig.",
      hwTitle: "Hardware besorgen",
      hwDesc: "Da alle diese Boards sehr beliebt sind, gehen wir davon aus, dass Sie sie bereits haben. Falls nicht, schauen Sie sich unser kostenloses Angebot unten an oder füllen Sie Ihre Schublade wieder auf.",
      hwLink: "Zum Shop",
      swTitle: "Software installieren",
      swDesc1: "Für den Bau Ihres eigenen Geräts in 3 Minuten können Sie aus einer breiten Auswahl an Sensoren wählen — z. B. Barometer, Hygrometer, Thermometer, Luxmeter, IR-Radiometer, Bewegungsmelder oder Anwesenheits-Taster.",
      swDesc2: "Verwenden Sie einfach die Install-For-Free-App direkt aus dem Browser, um nahtlos zwischen verschiedenen Gerätetypen zu wechseln. Keine Software-Installation auf dem PC erforderlich.",
      swLink: "Install-For-Free-App öffnen",
      housingTitle: "Gehäuse",
      housingDesc1: "Entdecken Sie die Freude an perfekter Individualisierung und entfalten Sie Ihr kreatives Potenzial — z. B. indem Sie die gebaute Elektronik in ein Gehäuse für Ihre Liebsten verpacken.",
      housingDesc2: "Sie können dies auf verschiedene Arten tun, z. B. mit einem handgemachten Kartongehäuse oder einem 3D-Druck.",
      housingLink: "3D-Druck-Gehäuse durchsuchen",
      smaTitle: "S-M-A Komponenten",
      smaDesc: "Zur Orientierung haben wir das Stapeln durch die Buchstaben S, M und A auf dem Triple-Adapter vereinfacht. Dies macht das Befestigen der drei Platinen so einfach wie möglich.",
      ecosystemTitle: "Vier Ökosystem-Optionen",
      ecosystemDesc: "Wählen Sie das Smart-Home-Ökosystem, das am besten zu Ihnen passt.",
      ecosystems: [
        { title: "Cloudfree", desc: "Das sicherste und einfachste Gerät hat keinerlei Internetverbindung. Sie installieren es und es funktioniert einfach. Ideal, wenn Sie keine Funktionen über die reine Messung hinaus benötigen." },
        { title: "Home Assistant", desc: "Home Assistant legt genau fest, welche Aktionen ausgeführt werden sollen, wenn ein Gerät eine bestimmte Situation erkennt. HA ist derzeit die weltweit beliebteste Umgebung für Smart-Home-Geräte." },
        { title: "IoT AppStore", desc: "Wenn Sie mehrere Geräte gemeinsam mit Over-the-Air-Updates steuern möchten, möglicherweise an entfernten Standorten (z. B. bei Ihren Eltern), ist die IoT-Lösung Ihre erste Wahl." },
        { title: "Matter", desc: "Matter ermöglicht die Integration Ihres Sensorgeräts mit bis zu fünf der beliebtesten Plattformen gleichzeitig — Amazon Alexa, Apple Home, Google Home, Samsung SmartThings oder Home Assistant." },
      ],
      statsTitle: "Erschließen Sie noch heute Ihre Möglichkeiten mit unserem modularen Ansatz!",
      stats: [
        { value: "28", label: "Sensoren" },
        { value: "5", label: "Mikrocontroller" },
        { value: "12", label: "Aktoren" },
        { value: "1500", label: "Lösungen" },
      ],
      greenTitle: "Green Modularity",
      greenDesc1: "Im Herzen unserer Innovation steht Green Modularity — ein bahnbrechendes Konzept, das Sensoren, Mikrocontroller und Aktoren (S-, M- & A-Platinen) als eigenständige, austauschbare Teile kombiniert und der Systematik jedes IoT-Produkts folgt.",
      greenDesc2: "Dieser Ansatz fördert Umweltverträglichkeit durch die Reduzierung von Elektronikschrott. Durch den Austausch einzelner Komponenten statt der Entsorgung ganzer Geräte verlängern wir die Produktlebensdauer und unterstützen die Kreislaufwirtschaft.",
      weeeTitle: "WEEE-Konformität",
      weeeDesc1: "Im Rahmen unseres Nachhaltigkeitsengagements erfüllen wir vollständig die WEEE-Richtlinie (Waste Electrical and Electronic Equipment). Diese stellt die ordnungsgemäße Sammlung, Verwertung und Entsorgung von Elektroprodukten sicher.",
      weeeDesc2: "Alle unsere Produkte tragen das Symbol der durchgestrichenen Mülltonne, das darauf hinweist, dass das Gerät nicht im Hausmüll entsorgt werden darf, sondern einer verantwortungsvollen Verwertung zugeführt werden muss.",
      weeeDesc3: "Da der Platz auf Leiterplatten (PCBs) begrenzt ist, ermöglichen wir den direkten Zugang zu dieser Nachhaltigkeitswebseite über einen QR-Code, der auf allen unseren PCBs aufgedruckt ist.",
      weeeNumber: "WEEE-Registrierungsnummer:",
      weeeCompany: "Carenuity handelnd als Chipglobe GmbH, Cincinnatistrasse 60, 81549 München, Deutschland",
      weeeContact: "info@chipglobe.com oder (+49) 89-1222469-40",
      greenClose: "Durch die Integration von Green Modularity in unsere Produktdesigns und die Einhaltung strenger Compliance-Protokolle stellen wir sicher, dass Nachhaltigkeit nicht nur ein Versprechen ist, sondern gelebte Praxis. Werden Sie Teil der Bewegung für einen intelligenteren, grüneren Planeten.",
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
